// Generated by CoffeeScript 1.11.1
(function() {
  var fade_dead_sprites, init_info, init_msg, init_sprite_div, render_background, render_hud, render_info, render_msg, render_sprites;

  window.init_graphics = function(go) {
    var bg, i, n_bg_imgs, name, score;
    for (name in go["sprites"]) {
      init_sprite_div(go, name);
    }
    if (go.hud != null) {
      go.hud.score.remove();
    }
    $('body').css({
      fontFamily: 'monospace'
    });
    score = $("<div>");
    score.css({
      position: "fixed",
      height: 50,
      width: 50,
      left: 25,
      top: go.h - 50,
      fontSize: 20
    });
    score.appendTo('body');
    go['hud'] = {
      score: score
    };
    $('body').css({
      position: 'fixed'
    });
    n_bg_imgs = 2;
    if (go.bg != null) {
      go.bg.remove();
    }
    i = Math.floor(Math.random() * n_bg_imgs);
    bg = $("<div>");
    bg.appendTo('body');
    go.bg = bg;
    bg.css({
      position: "fixed",
      height: "100vh",
      width: "100vw",
      zIndex: -100
    });
    fade_dead_sprites(go);
    init_info(go);
    return init_msg(go);
  };

  window.render = function(go) {
    render_background(go);
    render_sprites(go);
    render_hud(go);
    render_info(go);
    return render_msg(go);
  };

  init_msg = function(go) {
    var msg;
    if (go.msg == null) {
      msg = $('<div>');
      go['msg'] = msg;
      msg.appendTo('body');
      msg.css({
        position: 'fixed',
        top: go.h * 0.4,
        width: go.w,
        zIndex: -2,
        textAlign: 'center',
        fontSize: 28
      });
      return msg.html('go home');
    }
  };

  init_info = function(go) {
    var info;
    if (go.info == null) {
      info = $('<div>');
      go['info'] = info;
      info.appendTo('body');
      info.css({
        position: "absolute",
        overflow: 'scroll',
        height: go.h * 0.6,
        width: go.w * 0.6,
        padding: 15,
        marginTop: go.h * 0.2,
        marginLeft: go.w * 0.2,
        marginRight: go.w * 0.2,
        marginBottom: go.w * 0.2,
        fontSize: 25,
        background: '#fff'
      });
      return info.html('DANTE: DONT PLAY THIS  <br>Chase the ones that run away from you, <br>run from the ones that chase you, simple ;) <br>The numbers on the bottom left work like: <br>score // life // runners left <br><br>A: spawn a seed, warning: super growey  <br>S: spaw a repulsor, pushes things away <br>D: spa an attractor, like a mini black-hole <br>F: sp a chaser... he gonna get u <br>H: get back here 	<br><br>>> PRESS ANY KEY TO START <<<br>');
    }
  };

  render_msg = function(go) {
    var w1;
    w1 = (Math.sin(go.t / 100) + 1) / 2;
    go.msg.css({
      opacity: w1
    });
    if (go.msg.css('opacity') <= 0.01) {
      return go.msg.html('keep going');
    }
  };

  render_info = function(go) {
    if (go.paused) {
      return go.info.css({
        zIndex: 1
      });
    } else {
      return go.info.css({
        zIndex: -101
      });
    }
  };

  fade_dead_sprites = function(go) {
    var name, results, s;
    results = [];
    for (name in go.dead_sprites) {
      s = go.dead_sprites[name];
      if (s.div != null) {
        results.push(s.div.css({
          opacity: s.div.css('opacity') * 0.6,
          zIndex: -3
        }));
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  init_sprite_div = function(go, name) {
    var new_div, sprite;
    sprite = go["sprites"][name];
    new_div = $("<div>");
    new_div.css({
      position: "fixed",
      height: sprite["r"],
      width: sprite["r"],
      fill: sprite["img"],
      opacity: 1
    });
    $("body").append(new_div);
    return sprite["div"] = new_div;
  };

  render_background = function(go) {
    '	';
    var c, w1, w2;
    w1 = (Math.sin(go.t / 1000) + 1) / 2;
    w2 = (Math.cos(go.t / 5000) + 1) / 2;
    c = w1 * w2 * 240 + 120;
    return go.bg.css({
      background: 'hsl(' + c + ',100%,97%)'
    });
  };

  render_hud = function(go) {
    return go.hud.score.text(go.score + '//' + go.sprites.dante.r + '//' + go.n_run);
  };

  render_sprites = function(go) {
    var name, p, r, ref, results, s;
    results = [];
    for (name in go["sprites"]) {
      s = go["sprites"][name];
      if (s.div == null) {
        init_sprite_div(go, name);
      }
      s["div"].css({
        background: s["img"],
        fill: s["img"],
        left: s["cx"] - s["r"] / 2,
        top: s["cy"] - s["r"] / 2,
        height: s["r"],
        width: s["r"]
      });
      if (name === 'hit') {
        p = go.sprites.dante;
        r = p.r + 20;
        s.div.css({
          left: p.cx - r / 2,
          top: p.cy - r / 2,
          height: r,
          width: r
        });
        if (go.hit_ctr > 0) {
          s.div.css({
            background: go.hit_img
          });
        }
      }
      if ((ref = s.type) === 'repulsor' || ref === 'attractor' || ref === 'seed') {
        results.push(s.div.css({
          zIndex: -1
        }));
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

}).call(this);
